version: '3.0' 
services: 
   companyemployees: 
      image: redwood/companyemployees:runtime 
      build: 
         context: . 
      ports: 
         - "8080:5000"
      environment: 
         - ASPNETCORE_Kestrel__Certificates__Default__Password=awesomepass 
         - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/companyemployees.pfx 
      volumes: 
         - ${USERPROFILE}/.aspnet/https:/https/